config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :restaurants

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurant = Restaurant.new
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :index
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update_attributes!(restaurant_params)

    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id]).delete

    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:restaurant_name, :food_type)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudRestaurants</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
  <p>
    <%= f.label :restaurant_name %>
    <%= f.text_field :restaurant_name %>
  </p>
  <p>
    <%= f.label :food_type %>
    <%= f.text_field :food_type %>
  </p>
  <p>
    <%= f.submit 'Update restaurant' %>
  </p>
<% end %>

app/views/restaurants/index.html.erb
<%= form_for @restaurant do |f| %>
  <p>
    <%= f.label :restaurant_name %>
    <%= f.text_field :restaurant_name %>
  </p>
  <p>
    <%= f.label :food_type %>
    <%= f.text_field :food_type %>
  </p>
  <p>
    <%= f.submit 'Create a restaurant' %>
  </p>
<% end %>

<% @restaurants.each do |restaurant| %>
<ul>
  <li>
  <%= link_to "#{restaurant.restaurant_name}", restaurant_path(restaurant) %>, <%= restaurant.food_type %>
  </li>
</ul>
<% end %>

app/views/restaurants/show.html.erb
<ul>
  <li>
    <%= @restaurant.restaurant_name %>, <%= @restaurant.food_type %>
  </li>
</ul>

<%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete restaurant', restaurant_path(@restaurant), method: :delete %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add a restaurant', restaurants_path %>